"""
The ``add_integer`` module
======================

This module supplies tests for the function add_integer(). For example, we expect this to pass:

-------------------

>>> add_integer = __import__('0-add_integer').add_integer

    >>> add_integer(1, 5)
        6
    
    >>> add_integer(0.5, 0.5)
        1
    
    >>> add_integer("hello", 98)
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
    
    >>> add_integer("hello", "hello")
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        raise TypeError("b must be an integer")

    >>> add_integer()
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        raise TypeError("b must be an integer")
    
    >>> add_integer(,)
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        raise TypeError("b must be an integer")
    
    >>> add_integer(1, 2, 3)
            
    >>> add_integer()
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        raise TypeError("b must be an integer")

    >>> add_integer(a, b=98)
        Traceback (most recent call last):
        NameError: name 'a' is not defined
        ...
    
    >>> add_integer(None)
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        ...

    >>> add_integer("apple", b=98)
        Traceback (most recent call last):
        raise TypeError("a must be an integer")
        ...
    
    >>> add_integer(a=[key, value], b=98)
        Traceback (most recent call last):
        NameError: name 'key' is not defined
        ...

    >>> add_integer("-98", b=98)
        raise TypeError("a must be an integer")
        TypeError: a must be an integer
        ...

    >>> add_integer([1, 2, 3, 4], b=98)
        Traceback (most recent call last):
        TypeError: a must be an integer
        ...
    
    >>> add_integer(1e100, b=98)
        Traceback (most recent call last):
        TypeError: a must be an integer
        ...

